### ISSUE TITLE
Breaks when someone leaves the game

### ISSUE THREAD

**Issue by reisu1337** [reisu1337/BlockShuffle#2]
`[22:09:20 WARN]: [BlockShuffle] Task #133245 for BlockShuffle v0.2 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because the return value of "org.bukkit.Bukkit.getPlayer(java.util.UUID)" is null
        at tech.reisu1337.blockshuffle.events.PlayerListener.nextRound(PlayerListener.java:56) ~[blockshuffle-0.2.jar:?]
        at tech.reisu1337.blockshuffle.events.PlayerListener.lambda$nextRound$0(PlayerListener.java:72) ~[blockshuffle-0.2.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-172]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by reisu1337** [comment]
doesn't break anymore :)
