### ISSUE TITLE
Bossbar returning infinity error

### ISSUE THREAD

**Issue by reisu1337** [reisu1337/BlockShuffle#7]
`[16:07:02 WARN]: [BlockShuffle] Task #61456 for BlockShuffle v0.2 generated an exception
java.lang.IllegalArgumentException: Progress must be between 0.0 and 1.0 (-Infinity)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.17.1.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_17_R1.boss.CraftBossBar.setProgress(CraftBossBar.java:158) ~[patched_1.17.1.jar:git-Paper-172]
        at tech.reisu1337.blockshuffle.events.PlayerListener.decreaseBossBar(PlayerListener.java:117) ~[blockshuffle-0.2.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-172]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-172]`

**Comment by reisu1337** [comment]
done
